name: build

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
          cache: true
      -
        name: test
        run: go test -v ./...
      -
        name: setup cosign
        uses: sigstore/cosign-installer@v2.7.0
      -
        name: build snapshot
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/heads/')
        with:
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: archive binaries
        uses: actions/upload-artifact@v2
        with:
          retention-days: 5
          path: dist